version: "3.8"

services:
  postgres:
    image: postgres:14.10
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=vex

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "vex@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "vex"
    ports:
      - "80:80"
    depends_on:
        - postgres