version: "3.8"

services:
  postgres:
    container_name: vex-postgres
    image: postgres:14.10
    restart: always
    volumes:
      - ../vex/vex-db/init-databases:/docker-entrypoint-initdb.d
    ports:
      - "5430:5432"
    env_file: 
      - vex-db/.env.api-db

  pgadmin:
    container_name: vex-pgadmin
    image: dpage/pgadmin4
    env_file:
      - vex-db/.env.pgadmin
    ports:
      - "81:80"
    depends_on:
        - postgres

  zookeeper:
    container_name: vex-zookeeper
    image: confluentinc/cp-zookeeper:latest
    env_file:
      - .env.zookeeper
    ports:
      - 22181:2181
  
  kafka:
    container_name: vex-kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    env_file:
      - .env.kafka
