server:
  port: ${SERVER_PORT}

resources:
  folder: ${RESOURCES_FOLDER}

spring:
  datasource:
    url: jdbc:postgresql://${RESOURCE_DB_HOST}:${RESOURCE_DB_PORT}/${RESOURCE_DB_NAME}
    username: ${RESOURCE_DB_USER}
    password: ${RESOURCE_DB_PSW}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  batch:
    job:
      enabled: false
#    jdbc:
#      initialize-schema: always
