server:
  port: 8082

spring:
  cloud:
    gateway:
      routes:
        - id: resource-server
          uri: ${VEX_API}
          predicates:
            - Path=/vex/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/v1
            - AddRequestHeader=Vex-Application, vex
        - id: auth-server
          uri: http://localhost:9000
          predicates:
            - Path=/secret/**
          filters:
            - StripPrefix=1

# configure logging
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG